name: minimal_flutter_app
description: "A minimum flutter template."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.9.2
  path_provider: ^2.1.4
  http: ^1.2.2
  get: ^4.7.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  iconsax: ^0.0.8
  lottie: ^3.3.1
  data_table_2: ^2.6.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  get_storage: ^2.1.1
  marquee: ^2.3.0
  fl_chart: ^0.71.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  carousel_slider: ^5.0.0
  flutter_markdown: ^0.7.7
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.8.0
  mongo_dart: ^0.10.4

dependency_overrides:
  google_sign_in_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/loaders/
    - assets/logos/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700