name: minimal_flutter_app
description: "A minimum flutter template."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.9.2
  path_provider: ^2.1.4
  http: ^1.2.2
  get: ^4.7.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  iconsax: ^0.0.8
  lottie: ^3.3.1
  data_table_2: ^2.6.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/content/
    - assets/images/animations/
    - assets/logos/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700